# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rscapi.models.player_season_stats import PlayerSeasonStats  # noqa: E501

class TestPlayerSeasonStats(unittest.TestCase):
    """PlayerSeasonStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlayerSeasonStats:
        """Test PlayerSeasonStats
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlayerSeasonStats`
        """
        model = PlayerSeasonStats()  # noqa: E501
        if include_optional:
            return PlayerSeasonStats(
                id = 56,
                player = '0',
                season = 56,
                type = '0',
                shooting_percentage = 1.337,
                bpm = 1.337,
                bcpm = 1.337,
                avg_amount = 1.337,
                percent_zero_boost = 1.337,
                percent_full_boost = 1.337,
                percent_boost_0_25 = 1.337,
                percent_boost_25_50 = 1.337,
                percent_boost_50_75 = 1.337,
                percent_boost_75_100 = 1.337,
                avg_speed = 56,
                avg_powerslide_duration = 1.337,
                avg_speed_percentage = 1.337,
                percent_slow_speed = 1.337,
                percent_boost_speed = 1.337,
                percent_supersonic_speed = 1.337,
                percent_ground = 1.337,
                percent_low_air = 1.337,
                percent_high_air = 1.337,
                avg_distance_to_ball = 56,
                avg_distance_to_ball_possession = 56,
                avg_distance_to_ball_no_possession = 56,
                avg_distance_to_mates = 56,
                percent_defensive_third = 1.337,
                percent_offensive_third = 1.337,
                percent_neutral_third = 1.337,
                percent_defensive_half = 1.337,
                percent_offensive_half = 1.337,
                percent_behind_ball = 1.337,
                percent_infront_ball = 1.337,
                percent_most_back = 1.337,
                percent_most_forward = 1.337,
                percent_closest_to_ball = 1.337,
                percent_farthest_from_ball = 1.337,
                stats_type = 'REG',
                games_played = -2147483648,
                games_won = -2147483648,
                games_lost = -2147483648,
                mvps = -2147483648,
                shots = -2147483648,
                shots_against = -2147483648,
                goals = -2147483648,
                goals_against = -2147483648,
                saves = -2147483648,
                assists = -2147483648,
                points = -2147483648,
                hat_tricks = -2147483648,
                playmakers = -2147483648,
                saviors = -2147483648,
                goals_against_while_last_defender = -2147483648,
                time_powerslide = 1.337,
                count_powerslide = -2147483648,
                amount_collected = -2147483648,
                amount_stolen = -2147483648,
                amount_collected_big = -2147483648,
                amount_stolen_big = -2147483648,
                amount_collected_small = -2147483648,
                amount_stolen_small = -2147483648,
                count_collected_big = -2147483648,
                count_stolen_big = -2147483648,
                count_collected_small = -2147483648,
                count_stolen_small = -2147483648,
                amount_overfill = -2147483648,
                amount_overfill_stolen = -2147483648,
                amount_used_while_supersonic = -2147483648,
                time_zero_boost = 1.337,
                time_full_boost = 1.337,
                time_boost_0_25 = 1.337,
                time_boost_25_50 = 1.337,
                time_boost_50_75 = 1.337,
                time_boost_75_100 = 1.337,
                total_distance = -2147483648,
                time_supersonic_speed = 1.337,
                time_boost_speed = 1.337,
                time_slow_speed = 1.337,
                time_ground = 1.337,
                time_low_air = 1.337,
                time_high_air = 1.337,
                time_defensive_third = 1.337,
                time_neutral_third = 1.337,
                time_offensive_third = 1.337,
                time_defensive_half = 1.337,
                time_offensive_half = 1.337,
                time_behind_ball = 1.337,
                time_infront_ball = 1.337,
                time_most_back = 1.337,
                time_most_forward = 1.337,
                time_closest_to_ball = 1.337,
                time_farthest_from_ball = 1.337,
                demos_inflicted = -2147483648,
                demos_taken = -2147483648,
                raw_shooting_percentage = 1.337,
                raw_bpm = 1.337,
                raw_bcpm = 1.337,
                raw_avg_amount = 1.337,
                raw_percent_zero_boost = 1.337,
                raw_percent_full_boost = 1.337,
                raw_percent_boost_0_25 = 1.337,
                raw_percent_boost_25_50 = 1.337,
                raw_percent_boost_50_75 = 1.337,
                raw_percent_boost_75_100 = 1.337,
                raw_avg_speed = -2147483648,
                raw_avg_powerslide_duration = 1.337,
                raw_avg_speed_percentage = 1.337,
                raw_percent_slow_speed = 1.337,
                raw_percent_boost_speed = 1.337,
                raw_percent_supersonic_speed = 1.337,
                raw_percent_ground = 1.337,
                raw_percent_low_air = 1.337,
                raw_percent_high_air = 1.337,
                raw_avg_distance_to_ball = -2147483648,
                raw_avg_distance_to_ball_possession = -2147483648,
                raw_avg_distance_to_ball_no_possession = -2147483648,
                raw_avg_distance_to_mates = -2147483648,
                raw_percent_defensive_third = 1.337,
                raw_percent_offensive_third = 1.337,
                raw_percent_neutral_third = 1.337,
                raw_percent_defensive_half = 1.337,
                raw_percent_offensive_half = 1.337,
                raw_percent_behind_ball = 1.337,
                raw_percent_infront_ball = 1.337,
                raw_percent_most_back = 1.337,
                raw_percent_most_forward = 1.337,
                raw_percent_closest_to_ball = 1.337,
                raw_percent_farthest_from_ball = 1.337,
                tier = 56
            )
        else:
            return PlayerSeasonStats(
                player = '0',
                season = 56,
                type = '0',
                shooting_percentage = 1.337,
                bpm = 1.337,
                bcpm = 1.337,
                avg_amount = 1.337,
                percent_zero_boost = 1.337,
                percent_full_boost = 1.337,
                percent_boost_0_25 = 1.337,
                percent_boost_25_50 = 1.337,
                percent_boost_50_75 = 1.337,
                percent_boost_75_100 = 1.337,
                avg_speed = 56,
                avg_powerslide_duration = 1.337,
                avg_speed_percentage = 1.337,
                percent_slow_speed = 1.337,
                percent_boost_speed = 1.337,
                percent_supersonic_speed = 1.337,
                percent_ground = 1.337,
                percent_low_air = 1.337,
                percent_high_air = 1.337,
                avg_distance_to_ball = 56,
                avg_distance_to_ball_possession = 56,
                avg_distance_to_ball_no_possession = 56,
                avg_distance_to_mates = 56,
                percent_defensive_third = 1.337,
                percent_offensive_third = 1.337,
                percent_neutral_third = 1.337,
                percent_defensive_half = 1.337,
                percent_offensive_half = 1.337,
                percent_behind_ball = 1.337,
                percent_infront_ball = 1.337,
                percent_most_back = 1.337,
                percent_most_forward = 1.337,
                percent_closest_to_ball = 1.337,
                percent_farthest_from_ball = 1.337,
                tier = 56,
        )
        """

    def testPlayerSeasonStats(self):
        """Test PlayerSeasonStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
