# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.models.patched_league import PatchedLeague

class TestPatchedLeague(unittest.TestCase):
    """PatchedLeague unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchedLeague:
        """Test PatchedLeague
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchedLeague`
        """
        model = PatchedLeague()
        if include_optional:
            return PatchedLeague(
                id = 56,
                name = '',
                guild_id = 56,
                active = True,
                league_data = rscapi.models.league_data.LeagueData(
                    max_num_players = -2147483648, 
                    game_mode = '', 
                    match_format = -2147483648, ),
                tiers = [
                    rscapi.models.tier.Tier(
                        name = '', 
                        id = 56, 
                        color = 56, 
                        position = 56, )
                    ]
            )
        else:
            return PatchedLeague(
        )
        """

    def testPatchedLeague(self):
        """Test PatchedLeague"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
