# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.player_signup_schema import PlayerSignupSchema  # noqa: E501

class TestPlayerSignupSchema(unittest.TestCase):
    """PlayerSignupSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlayerSignupSchema:
        """Test PlayerSignupSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlayerSignupSchema`
        """
        model = PlayerSignupSchema()  # noqa: E501
        if include_optional:
            return PlayerSignupSchema(
                league = 56,
                tracker_links = [
                    ''
                    ],
                rsc_name = ''
            )
        else:
            return PlayerSignupSchema(
                league = 56,
                tracker_links = [
                    ''
                    ],
                rsc_name = '',
        )
        """

    def testPlayerSignupSchema(self):
        """Test PlayerSignupSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
