# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.models.create_member_input import CreateMemberInput

class TestCreateMemberInput(unittest.TestCase):
    """CreateMemberInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateMemberInput:
        """Test CreateMemberInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateMemberInput`
        """
        model = CreateMemberInput()
        if include_optional:
            return CreateMemberInput(
                username = '0',
                rsc_name = '0',
                discord_id = 56
            )
        else:
            return CreateMemberInput(
                username = '0',
                rsc_name = '0',
                discord_id = 56,
        )
        """

    def testCreateMemberInput(self):
        """Test CreateMemberInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
