# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.api.draft_picks_api import DraftPicksApi


class TestDraftPicksApi(unittest.TestCase):
    """DraftPicksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DraftPicksApi()

    def tearDown(self) -> None:
        pass

    def test_draft_picks_list(self) -> None:
        """Test case for draft_picks_list

        """
        pass

    def test_draft_picks_read(self) -> None:
        """Test case for draft_picks_read

        """
        pass

    def test_draft_picks_swap(self) -> None:
        """Test case for draft_picks_swap

        """
        pass


if __name__ == '__main__':
    unittest.main()
