# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.models.patched_elevated_role import PatchedElevatedRole

class TestPatchedElevatedRole(unittest.TestCase):
    """PatchedElevatedRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchedElevatedRole:
        """Test PatchedElevatedRole
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchedElevatedRole`
        """
        model = PatchedElevatedRole()
        if include_optional:
            return PatchedElevatedRole(
                id = 56,
                member = rscapi.models.simple_member.SimpleMember(
                    rsc_name = '', 
                    rsc_id = '', 
                    discord_id = -9223372036854776000, ),
                league = rscapi.models._elevated_role_league._ElevatedRoleLeague(
                    id = 56, 
                    name = '', 
                    guild_id = 56, 
                    active = True, ),
                position = '',
                gm = True,
                agm = True,
                arbiter = True,
                project_role = '',
                franchise_id = 56
            )
        else:
            return PatchedElevatedRole(
        )
        """

    def testPatchedElevatedRole(self):
        """Test PatchedElevatedRole"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
