# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rscapi.models.franchise import Franchise  # noqa: E501

class TestFranchise(unittest.TestCase):
    """Franchise unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Franchise:
        """Test Franchise
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Franchise`
        """
        model = Franchise()  # noqa: E501
        if include_optional:
            return Franchise(
                name = '0',
                prefix = '0',
                id = 56,
                gm = rscapi.models.franchise_gm.FranchiseGM(
                    rsc_name = '0', 
                    discord_id = 56, ),
                league = rscapi.models.league.League(
                    id = 56, 
                    name = '0', 
                    guild_id = 56, 
                    league_data = rscapi.models.league_data.LeagueData(
                        max_num_players = -2147483648, 
                        game_mode = '0', 
                        match_format = -2147483648, ), ),
                tiers = [
                    rscapi.models.franchise_tier.FranchiseTier(
                        name = '0', 
                        id = 56, )
                    ],
                active = True,
                teams = [
                    rscapi.models.team.Team(
                        id = 56, 
                        name = '0', 
                        franchise = '0', 
                        tier = '0', 
                        players = [
                            rscapi.models.player.Player(
                                id = 56, 
                                name = '0', 
                                status = '0', 
                                captain = True, 
                                base_mmr = 56, 
                                current_mmr = 56, 
                                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                discord_id = 56, )
                            ], 
                        latest_season = 56, )
                    ],
                logo = ''
            )
        else:
            return Franchise(
                name = '0',
                prefix = '0',
                league = rscapi.models.league.League(
                    id = 56, 
                    name = '0', 
                    guild_id = 56, 
                    league_data = rscapi.models.league_data.LeagueData(
                        max_num_players = -2147483648, 
                        game_mode = '0', 
                        match_format = -2147483648, ), ),
        )
        """

    def testFranchise(self):
        """Test Franchise"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
