# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rscapi.models.transfer_franchise import TransferFranchise  # noqa: E501

class TestTransferFranchise(unittest.TestCase):
    """TransferFranchise unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransferFranchise:
        """Test TransferFranchise
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransferFranchise`
        """
        model = TransferFranchise()  # noqa: E501
        if include_optional:
            return TransferFranchise(
                general_manager = 56,
                league = 56
            )
        else:
            return TransferFranchise(
                general_manager = 56,
                league = 56,
        )
        """

    def testTransferFranchise(self):
        """Test TransferFranchise"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
