# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.models.name_change_history import NameChangeHistory

class TestNameChangeHistory(unittest.TestCase):
    """NameChangeHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NameChangeHistory:
        """Test NameChangeHistory
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NameChangeHistory`
        """
        model = NameChangeHistory()
        if include_optional:
            return NameChangeHistory(
                old_name = '0',
                date_changed = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return NameChangeHistory(
                old_name = '0',
        )
        """

    def testNameChangeHistory(self):
        """Test NameChangeHistory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
