# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rscapi.models.trade_item import TradeItem  # noqa: E501

class TestTradeItem(unittest.TestCase):
    """TradeItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TradeItem:
        """Test TradeItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TradeItem`
        """
        model = TradeItem()  # noqa: E501
        if include_optional:
            return TradeItem(
                source = rscapi.models.franchise_identifier.Franchise Identifier(
                    gm = 56, 
                    name = '', 
                    id = 56, ),
                destination = rscapi.models.franchise_identifier.Franchise Identifier(
                    gm = 56, 
                    name = '', 
                    id = 56, ),
                value = rscapi.models.trade_value.Trade Value(
                    player = 56, 
                    pick = rscapi.models.draft_pick.Draft Pick(
                        tier = '', 
                        round = 56, 
                        number = 56, 
                        future = True, ), )
            )
        else:
            return TradeItem(
                source = rscapi.models.franchise_identifier.Franchise Identifier(
                    gm = 56, 
                    name = '', 
                    id = 56, ),
                destination = rscapi.models.franchise_identifier.Franchise Identifier(
                    gm = 56, 
                    name = '', 
                    id = 56, ),
                value = rscapi.models.trade_value.Trade Value(
                    player = 56, 
                    pick = rscapi.models.draft_pick.Draft Pick(
                        tier = '', 
                        round = 56, 
                        number = 56, 
                        future = True, ), ),
        )
        """

    def testTradeItem(self):
        """Test TradeItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
