# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.models.patched_member_name_change_request import PatchedMemberNameChangeRequest

class TestPatchedMemberNameChangeRequest(unittest.TestCase):
    """PatchedMemberNameChangeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchedMemberNameChangeRequest:
        """Test PatchedMemberNameChangeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchedMemberNameChangeRequest`
        """
        model = PatchedMemberNameChangeRequest()
        if include_optional:
            return PatchedMemberNameChangeRequest(
                name = '',
                admin_override = True
            )
        else:
            return PatchedMemberNameChangeRequest(
        )
        """

    def testPatchedMemberNameChangeRequest(self):
        """Test PatchedMemberNameChangeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
