# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.models.league_event_actor import LeagueEventActor

class TestLeagueEventActor(unittest.TestCase):
    """LeagueEventActor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LeagueEventActor:
        """Test LeagueEventActor
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LeagueEventActor`
        """
        model = LeagueEventActor()
        if include_optional:
            return LeagueEventActor(
                name = '0',
                discord_id = 56
            )
        else:
            return LeagueEventActor(
        )
        """

    def testLeagueEventActor(self):
        """Test LeagueEventActor"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
