# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.api.csv_api import CsvApi


class TestCsvApi(unittest.TestCase):
    """CsvApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CsvApi()

    def tearDown(self) -> None:
        pass

    def test_csv_franchise_contracts_data_list(self) -> None:
        """Test case for csv_franchise_contracts_data_list

        """
        pass

    def test_csv_franchise_contracts_data_read(self) -> None:
        """Test case for csv_franchise_contracts_data_read

        """
        pass

    def test_csv_master_member_sheet_list(self) -> None:
        """Test case for csv_master_member_sheet_list

        """
        pass

    def test_csv_master_member_sheet_read(self) -> None:
        """Test case for csv_master_member_sheet_read

        """
        pass

    def test_csv_teams_contracts_data_list(self) -> None:
        """Test case for csv_teams_contracts_data_list

        """
        pass

    def test_csv_teams_contracts_data_read(self) -> None:
        """Test case for csv_teams_contracts_data_read

        """
        pass

    def test_csv_tracker_links_data_list(self) -> None:
        """Test case for csv_tracker_links_data_list

        """
        pass

    def test_csv_tracker_links_data_read(self) -> None:
        """Test case for csv_tracker_links_data_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
