# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.models.elevated_role_input import ElevatedRoleInput

class TestElevatedRoleInput(unittest.TestCase):
    """ElevatedRoleInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ElevatedRoleInput:
        """Test ElevatedRoleInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ElevatedRoleInput`
        """
        model = ElevatedRoleInput()
        if include_optional:
            return ElevatedRoleInput(
                league = 56,
                position = 'TM',
                executor = 56,
                gm = True,
                agm = True,
                franchise = 56
            )
        else:
            return ElevatedRoleInput(
                league = 56,
                position = 'TM',
                executor = 56,
        )
        """

    def testElevatedRoleInput(self):
        """Test ElevatedRoleInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
