# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.models.draft_a_player_to_a_team import DraftAPlayerToATeam

class TestDraftAPlayerToATeam(unittest.TestCase):
    """DraftAPlayerToATeam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DraftAPlayerToATeam:
        """Test DraftAPlayerToATeam
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DraftAPlayerToATeam`
        """
        model = DraftAPlayerToATeam()
        if include_optional:
            return DraftAPlayerToATeam(
                player = 56,
                league = 56,
                team = '',
                executor = 56,
                admin_override = True,
                round = 56,
                number = 56
            )
        else:
            return DraftAPlayerToATeam(
        )
        """

    def testDraftAPlayerToATeam(self):
        """Test DraftAPlayerToATeam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
