# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rscapi.models.league_player import LeaguePlayer  # noqa: E501

class TestLeaguePlayer(unittest.TestCase):
    """LeaguePlayer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LeaguePlayer:
        """Test LeaguePlayer
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LeaguePlayer`
        """
        model = LeaguePlayer()  # noqa: E501
        if include_optional:
            return LeaguePlayer(
                id = 56,
                league = rscapi.models.league.League(
                    id = 56, 
                    name = '0', 
                    guild_id = 56, 
                    league_data = rscapi.models.league_data.LeagueData(
                        max_num_players = -2147483648, 
                        game_mode = '0', 
                        match_format = -2147483648, ), ),
                status = 'DE',
                season = 56,
                captain = True,
                base_mmr = 56,
                current_mmr = 56,
                contract_length = 56,
                team = rscapi.models.player_team.PlayerTeam(
                    name = '0', 
                    tier = '0', ),
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                previous_teams = [
                    rscapi.models.previous_team.PreviousTeam(
                        team = 56, 
                        sign_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        release_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        player = '0', )
                    ],
                player = rscapi.models.league_player_member.LeaguePlayerMember(
                    name = '0', 
                    rsc_id = '', )
            )
        else:
            return LeaguePlayer(
                league = rscapi.models.league.League(
                    id = 56, 
                    name = '0', 
                    guild_id = 56, 
                    league_data = rscapi.models.league_data.LeagueData(
                        max_num_players = -2147483648, 
                        game_mode = '0', 
                        match_format = -2147483648, ), ),
                season = 56,
                team = rscapi.models.player_team.PlayerTeam(
                    name = '0', 
                    tier = '0', ),
                previous_teams = [
                    rscapi.models.previous_team.PreviousTeam(
                        team = 56, 
                        sign_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        release_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        player = '0', )
                    ],
                player = rscapi.models.league_player_member.LeaguePlayerMember(
                    name = '0', 
                    rsc_id = '', ),
        )
        """

    def testLeaguePlayer(self):
        """Test LeaguePlayer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
