# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.models.team_player import TeamPlayer

class TestTeamPlayer(unittest.TestCase):
    """TeamPlayer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamPlayer:
        """Test TeamPlayer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamPlayer`
        """
        model = TeamPlayer()
        if include_optional:
            return TeamPlayer(
                id = 56,
                name = '',
                status = 'AR',
                captain = True,
                base_mmr = 56,
                current_mmr = 56,
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                discord_id = 56,
                sub_status = 0
            )
        else:
            return TeamPlayer(
                id = 56,
                name = '',
                status = 'AR',
                captain = True,
                base_mmr = 56,
                current_mmr = 56,
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                discord_id = 56,
                sub_status = 0,
        )
        """

    def testTeamPlayer(self):
        """Test TeamPlayer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
