# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rscapi.models.player_trade import PlayerTrade  # noqa: E501

class TestPlayerTrade(unittest.TestCase):
    """PlayerTrade unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlayerTrade:
        """Test PlayerTrade
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlayerTrade`
        """
        model = PlayerTrade()  # noqa: E501
        if include_optional:
            return PlayerTrade(
                first_player = 56,
                second_player = 56,
                league = 56,
                team = '',
                notes = '',
                executor = 56,
                admin_override = True
            )
        else:
            return PlayerTrade(
                league = 56,
                executor = 56,
        )
        """

    def testPlayerTrade(self):
        """Test PlayerTrade"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
