# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.models.paginated_transaction_response_list import PaginatedTransactionResponseList

class TestPaginatedTransactionResponseList(unittest.TestCase):
    """PaginatedTransactionResponseList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedTransactionResponseList:
        """Test PaginatedTransactionResponseList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedTransactionResponseList`
        """
        model = PaginatedTransactionResponseList()
        if include_optional:
            return PaginatedTransactionResponseList(
                count = 123,
                next = 'http://api.example.org/accounts/?offset=400&limit=100',
                previous = 'http://api.example.org/accounts/?offset=200&limit=100',
                results = [
                    rscapi.models.transaction_response.TransactionResponse(
                        player_updates = [
                            rscapi.models.player_transaction_updates.PlayerTransactionUpdates(
                                player = rscapi.models.league_player.LeaguePlayer(
                                    id = 56, 
                                    league = rscapi.models.league_player_league.LeaguePlayerLeague(
                                        id = 56, 
                                        name = '', 
                                        guild_id = -9223372036854776000, ), 
                                    status = null, 
                                    season = 56, 
                                    captain = True, 
                                    contract_length = -2147483648, 
                                    current_mmr = -2147483648, 
                                    base_mmr = -2147483648, 
                                    team = rscapi.models.player_team.PlayerTeam(
                                        name = '', 
                                        franchise = null, 
                                        id = 56, ), 
                                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    previous_teams = [
                                        rscapi.models.previous_team.PreviousTeam(
                                            team = rscapi.models.base_team.BaseTeam(
                                                id = 56, 
                                                name = '', ), 
                                            sign_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                            release_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                        ], 
                                    player = rscapi.models.league_player_member.LeaguePlayerMember(
                                        name = '', 
                                        rsc_id = '', 
                                        discord_id = 56, ), 
                                    tier = rscapi.models.tier.Tier(
                                        name = '', 
                                        id = 56, 
                                        color = 56, 
                                        position = 56, ), 
                                    sub_status = 0, 
                                    waiver_period_end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    signed_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                                old_team = rscapi.models.transaction_team.TransactionTeam(
                                    id = 56, 
                                    name = '', 
                                    tier = '', ), 
                                new_team = rscapi.models.transaction_team.TransactionTeam(
                                    id = 56, 
                                    name = '', 
                                    tier = '', ), )
                            ], 
                        pick_trades = [
                            rscapi.models.pick_transaction_updates.PickTransactionUpdates(
                                pick = rscapi.models.transaction_pick.TransactionPick(
                                    id = 56, 
                                    number = 56, 
                                    round = 56, 
                                    tier = '', 
                                    future_pick = True, 
                                    future_season = 56, 
                                    pick_from = '', 
                                    original_pick = '', ), 
                                source = rscapi.models.transaction_franchise.TransactionFranchise(
                                    gm = rscapi.models.franchise_gm.FranchiseGM(
                                        rsc_name = '', 
                                        discord_id = 56, ), 
                                    name = '', 
                                    id = 56, 
                                    prefix = '', ), 
                                destination = rscapi.models.transaction_franchise.TransactionFranchise(
                                    gm = rscapi.models.franchise_gm.FranchiseGM(
                                        rsc_name = '', 
                                        discord_id = 56, ), 
                                    name = '', 
                                    id = 56, 
                                    prefix = '', ), )
                            ], 
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        week = 'OFF', 
                        week_no = -2147483648, 
                        match_day = -2147483648, 
                        type = 'AIR', 
                        notes = '', 
                        first_franchise = , 
                        second_franchise = , 
                        executor = rscapi.models.simple_member.SimpleMember(
                            rsc_name = '', 
                            rsc_id = '', 
                            discord_id = -9223372036854776000, ), 
                        id = 56, )
                    ]
            )
        else:
            return PaginatedTransactionResponseList(
                count = 123,
                results = [
                    rscapi.models.transaction_response.TransactionResponse(
                        player_updates = [
                            rscapi.models.player_transaction_updates.PlayerTransactionUpdates(
                                player = rscapi.models.league_player.LeaguePlayer(
                                    id = 56, 
                                    league = rscapi.models.league_player_league.LeaguePlayerLeague(
                                        id = 56, 
                                        name = '', 
                                        guild_id = -9223372036854776000, ), 
                                    status = null, 
                                    season = 56, 
                                    captain = True, 
                                    contract_length = -2147483648, 
                                    current_mmr = -2147483648, 
                                    base_mmr = -2147483648, 
                                    team = rscapi.models.player_team.PlayerTeam(
                                        name = '', 
                                        franchise = null, 
                                        id = 56, ), 
                                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    previous_teams = [
                                        rscapi.models.previous_team.PreviousTeam(
                                            team = rscapi.models.base_team.BaseTeam(
                                                id = 56, 
                                                name = '', ), 
                                            sign_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                            release_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                        ], 
                                    player = rscapi.models.league_player_member.LeaguePlayerMember(
                                        name = '', 
                                        rsc_id = '', 
                                        discord_id = 56, ), 
                                    tier = rscapi.models.tier.Tier(
                                        name = '', 
                                        id = 56, 
                                        color = 56, 
                                        position = 56, ), 
                                    sub_status = 0, 
                                    waiver_period_end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    signed_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                                old_team = rscapi.models.transaction_team.TransactionTeam(
                                    id = 56, 
                                    name = '', 
                                    tier = '', ), 
                                new_team = rscapi.models.transaction_team.TransactionTeam(
                                    id = 56, 
                                    name = '', 
                                    tier = '', ), )
                            ], 
                        pick_trades = [
                            rscapi.models.pick_transaction_updates.PickTransactionUpdates(
                                pick = rscapi.models.transaction_pick.TransactionPick(
                                    id = 56, 
                                    number = 56, 
                                    round = 56, 
                                    tier = '', 
                                    future_pick = True, 
                                    future_season = 56, 
                                    pick_from = '', 
                                    original_pick = '', ), 
                                source = rscapi.models.transaction_franchise.TransactionFranchise(
                                    gm = rscapi.models.franchise_gm.FranchiseGM(
                                        rsc_name = '', 
                                        discord_id = 56, ), 
                                    name = '', 
                                    id = 56, 
                                    prefix = '', ), 
                                destination = rscapi.models.transaction_franchise.TransactionFranchise(
                                    gm = rscapi.models.franchise_gm.FranchiseGM(
                                        rsc_name = '', 
                                        discord_id = 56, ), 
                                    name = '', 
                                    id = 56, 
                                    prefix = '', ), )
                            ], 
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        week = 'OFF', 
                        week_no = -2147483648, 
                        match_day = -2147483648, 
                        type = 'AIR', 
                        notes = '', 
                        first_franchise = , 
                        second_franchise = , 
                        executor = rscapi.models.simple_member.SimpleMember(
                            rsc_name = '', 
                            rsc_id = '', 
                            discord_id = -9223372036854776000, ), 
                        id = 56, )
                    ],
        )
        """

    def testPaginatedTransactionResponseList(self):
        """Test PaginatedTransactionResponseList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
