# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.api.seasons_api import SeasonsApi  # noqa: E501


class TestSeasonsApi(unittest.TestCase):
    """SeasonsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SeasonsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_seasons_create(self) -> None:
        """Test case for seasons_create

        """
        pass

    def test_seasons_delete(self) -> None:
        """Test case for seasons_delete

        """
        pass

    def test_seasons_franchise_standings(self) -> None:
        """Test case for seasons_franchise_standings

        """
        pass

    def test_seasons_league_season(self) -> None:
        """Test case for seasons_league_season

        """
        pass

    def test_seasons_list(self) -> None:
        """Test case for seasons_list

        """
        pass

    def test_seasons_partial_update(self) -> None:
        """Test case for seasons_partial_update

        """
        pass

    def test_seasons_read(self) -> None:
        """Test case for seasons_read

        """
        pass

    def test_seasons_submit_schedule(self) -> None:
        """Test case for seasons_submit_schedule

        """
        pass

    def test_seasons_update(self) -> None:
        """Test case for seasons_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
