# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.models.flagged_match import FlaggedMatch

class TestFlaggedMatch(unittest.TestCase):
    """FlaggedMatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FlaggedMatch:
        """Test FlaggedMatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FlaggedMatch`
        """
        model = FlaggedMatch()
        if include_optional:
            return FlaggedMatch(
                id = 56,
                day = 56,
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                match_type = 'REG',
                match_type_label = '',
                tier = '',
                home_team = '',
                away_team = '',
                home_gm_discord_id = 56,
                away_gm_discord_id = 56,
                home_wins = 56,
                away_wins = 56,
                ballchasing_group = '',
                reported_games = 56,
                expected_games = 56,
                missing_result = True,
                missing_ballchasing_group = True,
                missing_stats = True
            )
        else:
            return FlaggedMatch(
                id = 56,
                day = 56,
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                match_type = 'REG',
                match_type_label = '',
                tier = '',
                home_team = '',
                away_team = '',
                home_gm_discord_id = 56,
                away_gm_discord_id = 56,
                home_wins = 56,
                away_wins = 56,
                ballchasing_group = '',
                reported_games = 56,
                expected_games = 56,
                missing_result = True,
                missing_ballchasing_group = True,
                missing_stats = True,
        )
        """

    def testFlaggedMatch(self):
        """Test FlaggedMatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
