# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.player_mmr import PlayerMMR  # noqa: E501

class TestPlayerMMR(unittest.TestCase):
    """PlayerMMR unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlayerMMR:
        """Test PlayerMMR
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlayerMMR`
        """
        model = PlayerMMR()  # noqa: E501
        if include_optional:
            return PlayerMMR(
                date_pulled = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tracker_link = openapi_client.models.tracker_mmr.TrackerMMR(
                    link = '0', ),
                threes_rating = -9223372036854775808,
                threes_season_peak = -9223372036854775808,
                threes_games_played = -9223372036854775808,
                twos_rating = -9223372036854775808,
                twos_season_peak = -9223372036854775808,
                twos_games_played = -9223372036854775808,
                ones_rating = -9223372036854775808,
                ones_season_peak = -9223372036854775808,
                ones_games_played = -9223372036854775808,
                notes = '0',
                member = '0',
                type = 'SN',
                rscid = '0'
            )
        else:
            return PlayerMMR(
                date_pulled = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tracker_link = openapi_client.models.tracker_mmr.TrackerMMR(
                    link = '0', ),
        )
        """

    def testPlayerMMR(self):
        """Test PlayerMMR"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
