# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.api.franchises_api import FranchisesApi  # noqa: E501


class TestFranchisesApi(unittest.TestCase):
    """FranchisesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FranchisesApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_franchises_create(self) -> None:
        """Test case for franchises_create

        """
        pass

    def test_franchises_delete(self) -> None:
        """Test case for franchises_delete

        """
        pass

    def test_franchises_list(self) -> None:
        """Test case for franchises_list

        """
        pass

    def test_franchises_partial_update(self) -> None:
        """Test case for franchises_partial_update

        """
        pass

    def test_franchises_read(self) -> None:
        """Test case for franchises_read

        """
        pass

    def test_franchises_transfer_franchise(self) -> None:
        """Test case for franchises_transfer_franchise

        """
        pass

    def test_franchises_update(self) -> None:
        """Test case for franchises_update

        """
        pass

    def test_franchises_upload_logo(self) -> None:
        """Test case for franchises_upload_logo

        """
        pass


if __name__ == '__main__':
    unittest.main()
