# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.models.ir_input import IRInput

class TestIRInput(unittest.TestCase):
    """IRInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IRInput:
        """Test IRInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IRInput`
        """
        model = IRInput()
        if include_optional:
            return IRInput(
                league = 56,
                executor = 56,
                admin_override = True,
                notes = 'API Transaction',
                player = 56,
                redshirt = True,
                remove_from_ir = True
            )
        else:
            return IRInput(
                league = 56,
                executor = 56,
                player = 56,
                remove_from_ir = True,
        )
        """

    def testIRInput(self):
        """Test IRInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
