# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rscapi.models.season import Season  # noqa: E501

class TestSeason(unittest.TestCase):
    """Season unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Season:
        """Test Season
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Season`
        """
        model = Season()  # noqa: E501
        if include_optional:
            return Season(
                league = rscapi.models.season_league.SeasonLeague(
                    name = '0', 
                    id = 56, ),
                number = 56,
                season_tier_data = [
                    rscapi.models.season_tier_data.SeasonTierData(
                        tier = '0', 
                        mmr_min = 56, 
                        mmr_max = 56, 
                        team_cap = 56, 
                        team_number = 56, 
                        schedule = rscapi.models.season_schedule.SeasonSchedule(
                            matches_per_season = 56, 
                            matches_per_night = 56, 
                            match_nights = '', ), )
                    ],
                current = True
            )
        else:
            return Season(
                league = rscapi.models.season_league.SeasonLeague(
                    name = '0', 
                    id = 56, ),
                season_tier_data = [
                    rscapi.models.season_tier_data.SeasonTierData(
                        tier = '0', 
                        mmr_min = 56, 
                        mmr_max = 56, 
                        team_cap = 56, 
                        team_number = 56, 
                        schedule = rscapi.models.season_schedule.SeasonSchedule(
                            matches_per_season = 56, 
                            matches_per_night = 56, 
                            match_nights = '', ), )
                    ],
        )
        """

    def testSeason(self):
        """Test Season"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
