# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.models.numbers_mmr_list200_response import NumbersMmrList200Response

class TestNumbersMmrList200Response(unittest.TestCase):
    """NumbersMmrList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NumbersMmrList200Response:
        """Test NumbersMmrList200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NumbersMmrList200Response`
        """
        model = NumbersMmrList200Response()
        if include_optional:
            return NumbersMmrList200Response(
                count = 56,
                next = '',
                previous = '',
                results = [
                    rscapi.models.player_mmr.PlayerMMR(
                        date_pulled = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        tracker_link = rscapi.models.tracker_mmr.TrackerMMR(
                            link = '0', ), 
                        threes_rating = -2147483648, 
                        threes_season_peak = -2147483648, 
                        threes_games_played = -2147483648, 
                        twos_rating = -2147483648, 
                        twos_season_peak = -2147483648, 
                        twos_games_played = -2147483648, 
                        ones_rating = -2147483648, 
                        ones_season_peak = -2147483648, 
                        ones_games_played = -2147483648, 
                        notes = '', 
                        psyonix_season = -2147483648, 
                        member = '0', 
                        type = 'SN', 
                        rscid = '0', )
                    ]
            )
        else:
            return NumbersMmrList200Response(
                count = 56,
                results = [
                    rscapi.models.player_mmr.PlayerMMR(
                        date_pulled = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        tracker_link = rscapi.models.tracker_mmr.TrackerMMR(
                            link = '0', ), 
                        threes_rating = -2147483648, 
                        threes_season_peak = -2147483648, 
                        threes_games_played = -2147483648, 
                        twos_rating = -2147483648, 
                        twos_season_peak = -2147483648, 
                        twos_games_played = -2147483648, 
                        ones_rating = -2147483648, 
                        ones_season_peak = -2147483648, 
                        ones_games_played = -2147483648, 
                        notes = '', 
                        psyonix_season = -2147483648, 
                        member = '0', 
                        type = 'SN', 
                        rscid = '0', )
                    ],
        )
        """

    def testNumbersMmrList200Response(self):
        """Test NumbersMmrList200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
