# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.models.paginated_name_change_history_list import PaginatedNameChangeHistoryList

class TestPaginatedNameChangeHistoryList(unittest.TestCase):
    """PaginatedNameChangeHistoryList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedNameChangeHistoryList:
        """Test PaginatedNameChangeHistoryList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedNameChangeHistoryList`
        """
        model = PaginatedNameChangeHistoryList()
        if include_optional:
            return PaginatedNameChangeHistoryList(
                count = 123,
                next = 'http://api.example.org/accounts/?offset=400&limit=100',
                previous = 'http://api.example.org/accounts/?offset=200&limit=100',
                results = [
                    rscapi.models.name_change_history.NameChangeHistory(
                        old_name = '', 
                        date_changed = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return PaginatedNameChangeHistoryList(
                count = 123,
                results = [
                    rscapi.models.name_change_history.NameChangeHistory(
                        old_name = '', 
                        date_changed = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testPaginatedNameChangeHistoryList(self):
        """Test PaginatedNameChangeHistoryList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
