# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.models.transaction_pick import TransactionPick

class TestTransactionPick(unittest.TestCase):
    """TransactionPick unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionPick:
        """Test TransactionPick
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionPick`
        """
        model = TransactionPick()
        if include_optional:
            return TransactionPick(
                id = 56,
                number = 56,
                round = 56,
                tier = '',
                future_pick = True,
                future_season = 56,
                pick_from = '0',
                original_pick = '0'
            )
        else:
            return TransactionPick(
        )
        """

    def testTransactionPick(self):
        """Test TransactionPick"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
