# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.models.tracker_peak import TrackerPeak

class TestTrackerPeak(unittest.TestCase):
    """TrackerPeak unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrackerPeak:
        """Test TrackerPeak
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrackerPeak`
        """
        model = TrackerPeak()
        if include_optional:
            return TrackerPeak(
                id = 56,
                rsc_id = '0',
                name = '0',
                discord_id = 56,
                status = 'FLD',
                pulls = 56,
                peaks = rscapi.models.peaks.Peaks()
            )
        else:
            return TrackerPeak(
        )
        """

    def testTrackerPeak(self):
        """Test TrackerPeak"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
