# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.models.waiver_claim_response import WaiverClaimResponse

class TestWaiverClaimResponse(unittest.TestCase):
    """WaiverClaimResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WaiverClaimResponse:
        """Test WaiverClaimResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WaiverClaimResponse`
        """
        model = WaiverClaimResponse()
        if include_optional:
            return WaiverClaimResponse(
                id = 56,
                season = 56,
                tier = 56,
                franchise = rscapi.models.transaction_franchise.TransactionFranchise(
                    gm = rscapi.models.franchise_gm.FranchiseGM(
                        rsc_name = '', 
                        discord_id = 56, ), 
                    name = '', 
                    id = 56, 
                    prefix = '', ),
                team = rscapi.models.transaction_team.TransactionTeam(
                    id = 56, 
                    name = '', 
                    tier = '', ),
                player = rscapi.models.league_player.LeaguePlayer(
                    id = 56, 
                    league = rscapi.models.league_player_league.LeaguePlayerLeague(
                        id = 56, 
                        name = '', 
                        guild_id = -9223372036854775808, ), 
                    status = null, 
                    season = 56, 
                    captain = True, 
                    contract_length = -2147483648, 
                    current_mmr = -2147483648, 
                    base_mmr = -2147483648, 
                    team = null, 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    previous_teams = [
                        rscapi.models.previous_team.PreviousTeam(
                            team = rscapi.models.base_team.BaseTeam(
                                id = 56, 
                                name = '', ), 
                            sign_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            release_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    player = rscapi.models.league_player_member.LeaguePlayerMember(
                        name = '', 
                        rsc_id = '', 
                        discord_id = 56, ), 
                    tier = null, 
                    sub_status = 0, 
                    waiver_period_end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    signed_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                drop_player = rscapi.models.league_player.LeaguePlayer(
                    id = 56, 
                    league = rscapi.models.league_player_league.LeaguePlayerLeague(
                        id = 56, 
                        name = '', 
                        guild_id = -9223372036854775808, ), 
                    status = null, 
                    season = 56, 
                    captain = True, 
                    contract_length = -2147483648, 
                    current_mmr = -2147483648, 
                    base_mmr = -2147483648, 
                    team = null, 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    previous_teams = [
                        rscapi.models.previous_team.PreviousTeam(
                            team = rscapi.models.base_team.BaseTeam(
                                id = 56, 
                                name = '', ), 
                            sign_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            release_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    player = rscapi.models.league_player_member.LeaguePlayerMember(
                        name = '', 
                        rsc_id = '', 
                        discord_id = 56, ), 
                    tier = null, 
                    sub_status = 0, 
                    waiver_period_end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    signed_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                status = 'pending',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return WaiverClaimResponse(
                franchise = rscapi.models.transaction_franchise.TransactionFranchise(
                    gm = rscapi.models.franchise_gm.FranchiseGM(
                        rsc_name = '', 
                        discord_id = 56, ), 
                    name = '', 
                    id = 56, 
                    prefix = '', ),
                team = rscapi.models.transaction_team.TransactionTeam(
                    id = 56, 
                    name = '', 
                    tier = '', ),
                player = rscapi.models.league_player.LeaguePlayer(
                    id = 56, 
                    league = rscapi.models.league_player_league.LeaguePlayerLeague(
                        id = 56, 
                        name = '', 
                        guild_id = -9223372036854775808, ), 
                    status = null, 
                    season = 56, 
                    captain = True, 
                    contract_length = -2147483648, 
                    current_mmr = -2147483648, 
                    base_mmr = -2147483648, 
                    team = null, 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    previous_teams = [
                        rscapi.models.previous_team.PreviousTeam(
                            team = rscapi.models.base_team.BaseTeam(
                                id = 56, 
                                name = '', ), 
                            sign_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            release_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    player = rscapi.models.league_player_member.LeaguePlayerMember(
                        name = '', 
                        rsc_id = '', 
                        discord_id = 56, ), 
                    tier = null, 
                    sub_status = 0, 
                    waiver_period_end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    signed_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                drop_player = rscapi.models.league_player.LeaguePlayer(
                    id = 56, 
                    league = rscapi.models.league_player_league.LeaguePlayerLeague(
                        id = 56, 
                        name = '', 
                        guild_id = -9223372036854775808, ), 
                    status = null, 
                    season = 56, 
                    captain = True, 
                    contract_length = -2147483648, 
                    current_mmr = -2147483648, 
                    base_mmr = -2147483648, 
                    team = null, 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    previous_teams = [
                        rscapi.models.previous_team.PreviousTeam(
                            team = rscapi.models.base_team.BaseTeam(
                                id = 56, 
                                name = '', ), 
                            sign_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            release_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    player = rscapi.models.league_player_member.LeaguePlayerMember(
                        name = '', 
                        rsc_id = '', 
                        discord_id = 56, ), 
                    tier = null, 
                    sub_status = 0, 
                    waiver_period_end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    signed_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
        )
        """

    def testWaiverClaimResponse(self):
        """Test WaiverClaimResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
