# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.models.week_enum import WeekEnum

class TestWeekEnum(unittest.TestCase):
    """WeekEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWeekEnum(self):
        """Test WeekEnum"""
        # inst = WeekEnum()

if __name__ == '__main__':
    unittest.main()
