# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.models.player_mmr_type_enum import PlayerMMRTypeEnum

class TestPlayerMMRTypeEnum(unittest.TestCase):
    """PlayerMMRTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlayerMMRTypeEnum(self):
        """Test PlayerMMRTypeEnum"""
        # inst = PlayerMMRTypeEnum()

if __name__ == '__main__':
    unittest.main()
