# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.models.tracker_link_status_enum import TrackerLinkStatusEnum

class TestTrackerLinkStatusEnum(unittest.TestCase):
    """TrackerLinkStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrackerLinkStatusEnum(self):
        """Test TrackerLinkStatusEnum"""
        # inst = TrackerLinkStatusEnum()

if __name__ == '__main__':
    unittest.main()
