# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rscapi.api.elevated_roles_api import ElevatedRolesApi


class TestElevatedRolesApi(unittest.IsolatedAsyncioTestCase):
    """ElevatedRolesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ElevatedRolesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_elevated_roles_list(self) -> None:
        """Test case for elevated_roles_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
