# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import datetime
from pydantic import Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import List, Optional
from typing_extensions import Annotated
from rscapi.models.league_event_detail import LeagueEventDetail
from rscapi.models.league_event_list import LeagueEventList

from rscapi.api_client import ApiClient, RequestSerialized
from rscapi.api_response import ApiResponse
from rscapi.rest import RESTResponseType


class IntegrationsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    async def integrations_events_list(
        self,
        id__gte: Annotated[Optional[StrictInt], Field(description="Event ID greater than or equal to this value.")] = None,
        league: Annotated[Optional[StrictInt], Field(description="League ID.")] = None,
        category: Annotated[Optional[StrictStr], Field(description="Event category code.")] = None,
        action: Annotated[Optional[StrictStr], Field(description="Event action code.")] = None,
        is_public: Annotated[Optional[StrictBool], Field(description="Filter events by public visibility.")] = None,
        created_at__gte: Annotated[Optional[datetime], Field(description="Events created at or after this datetime (ISO 8601).")] = None,
        created_at__lte: Annotated[Optional[datetime], Field(description="Events created at or before this datetime (ISO 8601).")] = None,
        guild_id: Annotated[Optional[StrictInt], Field(description="Discord guild ID for league-scoped events.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[LeagueEventList]:
        """integrations_events_list


        :param id__gte: Event ID greater than or equal to this value.
        :type id__gte: int
        :param league: League ID.
        :type league: int
        :param category: Event category code.
        :type category: str
        :param action: Event action code.
        :type action: str
        :param is_public: Filter events by public visibility.
        :type is_public: bool
        :param created_at__gte: Events created at or after this datetime (ISO 8601).
        :type created_at__gte: datetime
        :param created_at__lte: Events created at or before this datetime (ISO 8601).
        :type created_at__lte: datetime
        :param guild_id: Discord guild ID for league-scoped events.
        :type guild_id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._integrations_events_list_serialize(
            id__gte=id__gte,
            league=league,
            category=category,
            action=action,
            is_public=is_public,
            created_at__gte=created_at__gte,
            created_at__lte=created_at__lte,
            guild_id=guild_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[LeagueEventList]",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def integrations_events_list_with_http_info(
        self,
        id__gte: Annotated[Optional[StrictInt], Field(description="Event ID greater than or equal to this value.")] = None,
        league: Annotated[Optional[StrictInt], Field(description="League ID.")] = None,
        category: Annotated[Optional[StrictStr], Field(description="Event category code.")] = None,
        action: Annotated[Optional[StrictStr], Field(description="Event action code.")] = None,
        is_public: Annotated[Optional[StrictBool], Field(description="Filter events by public visibility.")] = None,
        created_at__gte: Annotated[Optional[datetime], Field(description="Events created at or after this datetime (ISO 8601).")] = None,
        created_at__lte: Annotated[Optional[datetime], Field(description="Events created at or before this datetime (ISO 8601).")] = None,
        guild_id: Annotated[Optional[StrictInt], Field(description="Discord guild ID for league-scoped events.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[LeagueEventList]]:
        """integrations_events_list


        :param id__gte: Event ID greater than or equal to this value.
        :type id__gte: int
        :param league: League ID.
        :type league: int
        :param category: Event category code.
        :type category: str
        :param action: Event action code.
        :type action: str
        :param is_public: Filter events by public visibility.
        :type is_public: bool
        :param created_at__gte: Events created at or after this datetime (ISO 8601).
        :type created_at__gte: datetime
        :param created_at__lte: Events created at or before this datetime (ISO 8601).
        :type created_at__lte: datetime
        :param guild_id: Discord guild ID for league-scoped events.
        :type guild_id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._integrations_events_list_serialize(
            id__gte=id__gte,
            league=league,
            category=category,
            action=action,
            is_public=is_public,
            created_at__gte=created_at__gte,
            created_at__lte=created_at__lte,
            guild_id=guild_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[LeagueEventList]",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def integrations_events_list_without_preload_content(
        self,
        id__gte: Annotated[Optional[StrictInt], Field(description="Event ID greater than or equal to this value.")] = None,
        league: Annotated[Optional[StrictInt], Field(description="League ID.")] = None,
        category: Annotated[Optional[StrictStr], Field(description="Event category code.")] = None,
        action: Annotated[Optional[StrictStr], Field(description="Event action code.")] = None,
        is_public: Annotated[Optional[StrictBool], Field(description="Filter events by public visibility.")] = None,
        created_at__gte: Annotated[Optional[datetime], Field(description="Events created at or after this datetime (ISO 8601).")] = None,
        created_at__lte: Annotated[Optional[datetime], Field(description="Events created at or before this datetime (ISO 8601).")] = None,
        guild_id: Annotated[Optional[StrictInt], Field(description="Discord guild ID for league-scoped events.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """integrations_events_list


        :param id__gte: Event ID greater than or equal to this value.
        :type id__gte: int
        :param league: League ID.
        :type league: int
        :param category: Event category code.
        :type category: str
        :param action: Event action code.
        :type action: str
        :param is_public: Filter events by public visibility.
        :type is_public: bool
        :param created_at__gte: Events created at or after this datetime (ISO 8601).
        :type created_at__gte: datetime
        :param created_at__lte: Events created at or before this datetime (ISO 8601).
        :type created_at__lte: datetime
        :param guild_id: Discord guild ID for league-scoped events.
        :type guild_id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._integrations_events_list_serialize(
            id__gte=id__gte,
            league=league,
            category=category,
            action=action,
            is_public=is_public,
            created_at__gte=created_at__gte,
            created_at__lte=created_at__lte,
            guild_id=guild_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[LeagueEventList]",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _integrations_events_list_serialize(
        self,
        id__gte,
        league,
        category,
        action,
        is_public,
        created_at__gte,
        created_at__lte,
        guild_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if id__gte is not None:
            
            _query_params.append(('id__gte', id__gte))
            
        if league is not None:
            
            _query_params.append(('league', league))
            
        if category is not None:
            
            _query_params.append(('category', category))
            
        if action is not None:
            
            _query_params.append(('action', action))
            
        if is_public is not None:
            
            _query_params.append(('is_public', is_public))
            
        if created_at__gte is not None:
            if isinstance(created_at__gte, datetime):
                _query_params.append(
                    (
                        'created_at__gte',
                        created_at__gte.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('created_at__gte', created_at__gte))
            
        if created_at__lte is not None:
            if isinstance(created_at__lte, datetime):
                _query_params.append(
                    (
                        'created_at__lte',
                        created_at__lte.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('created_at__lte', created_at__lte))
            
        if guild_id is not None:
            
            _query_params.append(('guild_id', guild_id))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'Api-Key'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/integrations/events/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    async def integrations_events_read(
        self,
        id: Annotated[StrictInt, Field(description="A unique integer value identifying this league event.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> LeagueEventDetail:
        """integrations_events_read


        :param id: A unique integer value identifying this league event. (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._integrations_events_read_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "LeagueEventDetail",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def integrations_events_read_with_http_info(
        self,
        id: Annotated[StrictInt, Field(description="A unique integer value identifying this league event.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[LeagueEventDetail]:
        """integrations_events_read


        :param id: A unique integer value identifying this league event. (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._integrations_events_read_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "LeagueEventDetail",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def integrations_events_read_without_preload_content(
        self,
        id: Annotated[StrictInt, Field(description="A unique integer value identifying this league event.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """integrations_events_read


        :param id: A unique integer value identifying this league event. (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._integrations_events_read_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "LeagueEventDetail",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _integrations_events_read_serialize(
        self,
        id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'Api-Key'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/integrations/events/{id}/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


