"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import List, Optional
from typing_extensions import Annotated
from rscapi.models.flagged_match import FlaggedMatch
from rscapi.models.paginated_flagged_match_list import PaginatedFlaggedMatchList
from rscapi.models.sbv_result import SBVResult

from rscapi.api_client import ApiClient, RequestSerialized
from rscapi.api_response import ApiResponse
from rscapi.rest import RESTResponseType


class StatsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    async def stats_flagged_matches_list(
        self,
        day: Annotated[Optional[StrictInt], Field(description="Match day")] = None,
        league: Annotated[Optional[StrictInt], Field(description="League ID")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Number of results to return per page.")] = None,
        match_type: Annotated[Optional[StrictStr], Field(description="Match type filter")] = None,
        missing_ballchasing_group: Annotated[Optional[StrictBool], Field(description="Filter by missing ballchasing group flag")] = None,
        missing_result: Annotated[Optional[StrictBool], Field(description="Filter by missing result flag")] = None,
        missing_stats: Annotated[Optional[StrictBool], Field(description="Filter by missing stats flag")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="The initial index from which to return the results.")] = None,
        search: Annotated[Optional[StrictStr], Field(description="Case-insensitive search across team and franchise names")] = None,
        season: Annotated[Optional[StrictInt], Field(description="Season ID")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> PaginatedFlaggedMatchList:
        """stats_flagged_matches_list


        :param day: Match day
        :type day: int
        :param league: League ID
        :type league: int
        :param limit: Number of results to return per page.
        :type limit: int
        :param match_type: Match type filter
        :type match_type: str
        :param missing_ballchasing_group: Filter by missing ballchasing group flag
        :type missing_ballchasing_group: bool
        :param missing_result: Filter by missing result flag
        :type missing_result: bool
        :param missing_stats: Filter by missing stats flag
        :type missing_stats: bool
        :param offset: The initial index from which to return the results.
        :type offset: int
        :param search: Case-insensitive search across team and franchise names
        :type search: str
        :param season: Season ID
        :type season: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._stats_flagged_matches_list_serialize(
            day=day,
            league=league,
            limit=limit,
            match_type=match_type,
            missing_ballchasing_group=missing_ballchasing_group,
            missing_result=missing_result,
            missing_stats=missing_stats,
            offset=offset,
            search=search,
            season=season,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaginatedFlaggedMatchList",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def stats_flagged_matches_list_with_http_info(
        self,
        day: Annotated[Optional[StrictInt], Field(description="Match day")] = None,
        league: Annotated[Optional[StrictInt], Field(description="League ID")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Number of results to return per page.")] = None,
        match_type: Annotated[Optional[StrictStr], Field(description="Match type filter")] = None,
        missing_ballchasing_group: Annotated[Optional[StrictBool], Field(description="Filter by missing ballchasing group flag")] = None,
        missing_result: Annotated[Optional[StrictBool], Field(description="Filter by missing result flag")] = None,
        missing_stats: Annotated[Optional[StrictBool], Field(description="Filter by missing stats flag")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="The initial index from which to return the results.")] = None,
        search: Annotated[Optional[StrictStr], Field(description="Case-insensitive search across team and franchise names")] = None,
        season: Annotated[Optional[StrictInt], Field(description="Season ID")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[PaginatedFlaggedMatchList]:
        """stats_flagged_matches_list


        :param day: Match day
        :type day: int
        :param league: League ID
        :type league: int
        :param limit: Number of results to return per page.
        :type limit: int
        :param match_type: Match type filter
        :type match_type: str
        :param missing_ballchasing_group: Filter by missing ballchasing group flag
        :type missing_ballchasing_group: bool
        :param missing_result: Filter by missing result flag
        :type missing_result: bool
        :param missing_stats: Filter by missing stats flag
        :type missing_stats: bool
        :param offset: The initial index from which to return the results.
        :type offset: int
        :param search: Case-insensitive search across team and franchise names
        :type search: str
        :param season: Season ID
        :type season: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._stats_flagged_matches_list_serialize(
            day=day,
            league=league,
            limit=limit,
            match_type=match_type,
            missing_ballchasing_group=missing_ballchasing_group,
            missing_result=missing_result,
            missing_stats=missing_stats,
            offset=offset,
            search=search,
            season=season,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaginatedFlaggedMatchList",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def stats_flagged_matches_list_without_preload_content(
        self,
        day: Annotated[Optional[StrictInt], Field(description="Match day")] = None,
        league: Annotated[Optional[StrictInt], Field(description="League ID")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Number of results to return per page.")] = None,
        match_type: Annotated[Optional[StrictStr], Field(description="Match type filter")] = None,
        missing_ballchasing_group: Annotated[Optional[StrictBool], Field(description="Filter by missing ballchasing group flag")] = None,
        missing_result: Annotated[Optional[StrictBool], Field(description="Filter by missing result flag")] = None,
        missing_stats: Annotated[Optional[StrictBool], Field(description="Filter by missing stats flag")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="The initial index from which to return the results.")] = None,
        search: Annotated[Optional[StrictStr], Field(description="Case-insensitive search across team and franchise names")] = None,
        season: Annotated[Optional[StrictInt], Field(description="Season ID")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """stats_flagged_matches_list


        :param day: Match day
        :type day: int
        :param league: League ID
        :type league: int
        :param limit: Number of results to return per page.
        :type limit: int
        :param match_type: Match type filter
        :type match_type: str
        :param missing_ballchasing_group: Filter by missing ballchasing group flag
        :type missing_ballchasing_group: bool
        :param missing_result: Filter by missing result flag
        :type missing_result: bool
        :param missing_stats: Filter by missing stats flag
        :type missing_stats: bool
        :param offset: The initial index from which to return the results.
        :type offset: int
        :param search: Case-insensitive search across team and franchise names
        :type search: str
        :param season: Season ID
        :type season: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._stats_flagged_matches_list_serialize(
            day=day,
            league=league,
            limit=limit,
            match_type=match_type,
            missing_ballchasing_group=missing_ballchasing_group,
            missing_result=missing_result,
            missing_stats=missing_stats,
            offset=offset,
            search=search,
            season=season,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaginatedFlaggedMatchList",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _stats_flagged_matches_list_serialize(
        self,
        day,
        league,
        limit,
        match_type,
        missing_ballchasing_group,
        missing_result,
        missing_stats,
        offset,
        search,
        season,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if day is not None:
            
            _query_params.append(('day', day))
            
        if league is not None:
            
            _query_params.append(('league', league))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if match_type is not None:
            
            _query_params.append(('match_type', match_type))
            
        if missing_ballchasing_group is not None:
            
            _query_params.append(('missing_ballchasing_group', missing_ballchasing_group))
            
        if missing_result is not None:
            
            _query_params.append(('missing_result', missing_result))
            
        if missing_stats is not None:
            
            _query_params.append(('missing_stats', missing_stats))
            
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        if search is not None:
            
            _query_params.append(('search', search))
            
        if season is not None:
            
            _query_params.append(('season', season))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'Api-Key'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/stats/flagged-matches/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    async def stats_flagged_matches_retrieve(
        self,
        id: Annotated[StrictInt, Field(description="A unique integer value identifying this match.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> FlaggedMatch:
        """stats_flagged_matches_retrieve


        :param id: A unique integer value identifying this match. (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._stats_flagged_matches_retrieve_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "FlaggedMatch",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def stats_flagged_matches_retrieve_with_http_info(
        self,
        id: Annotated[StrictInt, Field(description="A unique integer value identifying this match.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[FlaggedMatch]:
        """stats_flagged_matches_retrieve


        :param id: A unique integer value identifying this match. (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._stats_flagged_matches_retrieve_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "FlaggedMatch",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def stats_flagged_matches_retrieve_without_preload_content(
        self,
        id: Annotated[StrictInt, Field(description="A unique integer value identifying this match.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """stats_flagged_matches_retrieve


        :param id: A unique integer value identifying this match. (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._stats_flagged_matches_retrieve_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "FlaggedMatch",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _stats_flagged_matches_retrieve_serialize(
        self,
        id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'Api-Key'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/stats/flagged-matches/{id}/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    async def stats_sbv_list(
        self,
        league: Annotated[int, Field(strict=True, ge=1, description="League ID")],
        season: Annotated[int, Field(strict=True, ge=1, description="Season ID")],
        tier: Annotated[int, Field(strict=True, ge=1, description="Tier ID")],
        stats_type: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True)]], Field(description="Stats type filter  * `REG` - Regular Season Stats * `PST` - Post Season Stats")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[SBVResult]:
        """stats_sbv_list


        :param league: League ID (required)
        :type league: int
        :param season: Season ID (required)
        :type season: int
        :param tier: Tier ID (required)
        :type tier: int
        :param stats_type: Stats type filter  * `REG` - Regular Season Stats * `PST` - Post Season Stats
        :type stats_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._stats_sbv_list_serialize(
            league=league,
            season=season,
            tier=tier,
            stats_type=stats_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[SBVResult]",
            '400': "Error",
            '404': "Error",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def stats_sbv_list_with_http_info(
        self,
        league: Annotated[int, Field(strict=True, ge=1, description="League ID")],
        season: Annotated[int, Field(strict=True, ge=1, description="Season ID")],
        tier: Annotated[int, Field(strict=True, ge=1, description="Tier ID")],
        stats_type: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True)]], Field(description="Stats type filter  * `REG` - Regular Season Stats * `PST` - Post Season Stats")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[SBVResult]]:
        """stats_sbv_list


        :param league: League ID (required)
        :type league: int
        :param season: Season ID (required)
        :type season: int
        :param tier: Tier ID (required)
        :type tier: int
        :param stats_type: Stats type filter  * `REG` - Regular Season Stats * `PST` - Post Season Stats
        :type stats_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._stats_sbv_list_serialize(
            league=league,
            season=season,
            tier=tier,
            stats_type=stats_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[SBVResult]",
            '400': "Error",
            '404': "Error",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def stats_sbv_list_without_preload_content(
        self,
        league: Annotated[int, Field(strict=True, ge=1, description="League ID")],
        season: Annotated[int, Field(strict=True, ge=1, description="Season ID")],
        tier: Annotated[int, Field(strict=True, ge=1, description="Tier ID")],
        stats_type: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True)]], Field(description="Stats type filter  * `REG` - Regular Season Stats * `PST` - Post Season Stats")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """stats_sbv_list


        :param league: League ID (required)
        :type league: int
        :param season: Season ID (required)
        :type season: int
        :param tier: Tier ID (required)
        :type tier: int
        :param stats_type: Stats type filter  * `REG` - Regular Season Stats * `PST` - Post Season Stats
        :type stats_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._stats_sbv_list_serialize(
            league=league,
            season=season,
            tier=tier,
            stats_type=stats_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[SBVResult]",
            '400': "Error",
            '404': "Error",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _stats_sbv_list_serialize(
        self,
        league,
        season,
        tier,
        stats_type,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if league is not None:
            
            _query_params.append(('league', league))
            
        if season is not None:
            
            _query_params.append(('season', season))
            
        if stats_type is not None:
            
            _query_params.append(('stats_type', stats_type))
            
        if tier is not None:
            
            _query_params.append(('tier', tier))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'Api-Key'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/stats/sbv/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    async def stats_sbv_retrieve(
        self,
        id: Annotated[StrictInt, Field(description="A unique integer value identifying this league player.")],
        league: Annotated[int, Field(strict=True, ge=1, description="League ID")],
        pk: Annotated[StrictStr, Field(description="LeaguePlayer ID or Member discord_id")],
        season: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Season Number (alias)")] = None,
        season_id: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Season ID")] = None,
        season_number: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Season Number")] = None,
        stats_type: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True)]], Field(description="Stats type filter  * `REG` - Regular Season Stats * `PST` - Post Season Stats")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> SBVResult:
        """stats_sbv_retrieve


        :param id: A unique integer value identifying this league player. (required)
        :type id: int
        :param league: League ID (required)
        :type league: int
        :param pk: LeaguePlayer ID or Member discord_id (required)
        :type pk: str
        :param season: Season Number (alias)
        :type season: int
        :param season_id: Season ID
        :type season_id: int
        :param season_number: Season Number
        :type season_number: int
        :param stats_type: Stats type filter  * `REG` - Regular Season Stats * `PST` - Post Season Stats
        :type stats_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._stats_sbv_retrieve_serialize(
            id=id,
            league=league,
            pk=pk,
            season=season,
            season_id=season_id,
            season_number=season_number,
            stats_type=stats_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SBVResult",
            '400': "Error",
            '404': "Error",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def stats_sbv_retrieve_with_http_info(
        self,
        id: Annotated[StrictInt, Field(description="A unique integer value identifying this league player.")],
        league: Annotated[int, Field(strict=True, ge=1, description="League ID")],
        pk: Annotated[StrictStr, Field(description="LeaguePlayer ID or Member discord_id")],
        season: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Season Number (alias)")] = None,
        season_id: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Season ID")] = None,
        season_number: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Season Number")] = None,
        stats_type: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True)]], Field(description="Stats type filter  * `REG` - Regular Season Stats * `PST` - Post Season Stats")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[SBVResult]:
        """stats_sbv_retrieve


        :param id: A unique integer value identifying this league player. (required)
        :type id: int
        :param league: League ID (required)
        :type league: int
        :param pk: LeaguePlayer ID or Member discord_id (required)
        :type pk: str
        :param season: Season Number (alias)
        :type season: int
        :param season_id: Season ID
        :type season_id: int
        :param season_number: Season Number
        :type season_number: int
        :param stats_type: Stats type filter  * `REG` - Regular Season Stats * `PST` - Post Season Stats
        :type stats_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._stats_sbv_retrieve_serialize(
            id=id,
            league=league,
            pk=pk,
            season=season,
            season_id=season_id,
            season_number=season_number,
            stats_type=stats_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SBVResult",
            '400': "Error",
            '404': "Error",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def stats_sbv_retrieve_without_preload_content(
        self,
        id: Annotated[StrictInt, Field(description="A unique integer value identifying this league player.")],
        league: Annotated[int, Field(strict=True, ge=1, description="League ID")],
        pk: Annotated[StrictStr, Field(description="LeaguePlayer ID or Member discord_id")],
        season: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Season Number (alias)")] = None,
        season_id: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Season ID")] = None,
        season_number: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Season Number")] = None,
        stats_type: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True)]], Field(description="Stats type filter  * `REG` - Regular Season Stats * `PST` - Post Season Stats")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """stats_sbv_retrieve


        :param id: A unique integer value identifying this league player. (required)
        :type id: int
        :param league: League ID (required)
        :type league: int
        :param pk: LeaguePlayer ID or Member discord_id (required)
        :type pk: str
        :param season: Season Number (alias)
        :type season: int
        :param season_id: Season ID
        :type season_id: int
        :param season_number: Season Number
        :type season_number: int
        :param stats_type: Stats type filter  * `REG` - Regular Season Stats * `PST` - Post Season Stats
        :type stats_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._stats_sbv_retrieve_serialize(
            id=id,
            league=league,
            pk=pk,
            season=season,
            season_id=season_id,
            season_number=season_number,
            stats_type=stats_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SBVResult",
            '400': "Error",
            '404': "Error",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _stats_sbv_retrieve_serialize(
        self,
        id,
        league,
        pk,
        season,
        season_id,
        season_number,
        stats_type,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        if pk is not None:
            _path_params['pk'] = pk
        # process the query parameters
        if league is not None:
            
            _query_params.append(('league', league))
            
        if season is not None:
            
            _query_params.append(('season', season))
            
        if season_id is not None:
            
            _query_params.append(('season_id', season_id))
            
        if season_number is not None:
            
            _query_params.append(('season_number', season_number))
            
        if stats_type is not None:
            
            _query_params.append(('stats_type', stats_type))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'Api-Key'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/stats/sbv/{id}/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


