# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from rscapi.models.draft_pick_franchise import DraftPickFranchise
from rscapi.models.draft_pick_league_player import DraftPickLeaguePlayer
from rscapi.models.season_draft_pick_list import SeasonDraftPickList
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DraftPickDetails(BaseModel):
    """
    DraftPickDetails
    """ # noqa: E501
    id: Optional[StrictInt] = None
    round: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = Field(default=None, description="Specific round in the tier.")
    number: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = Field(default=None, description="Pick in the specific tier.")
    tier: SeasonDraftPickList
    franchise: DraftPickFranchise
    future_pick: Optional[StrictBool] = None
    deleted: Optional[StrictBool] = Field(default=None, description="Is this pick removed because someone lost a tier.")
    pick_from: Optional[Dict[str, Any]] = None
    original_pick: Optional[Dict[str, Any]] = None
    future_season: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    players: List[DraftPickLeaguePlayer]
    __properties: ClassVar[List[str]] = ["id", "round", "number", "tier", "franchise", "future_pick", "deleted", "pick_from", "original_pick", "future_season", "players"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DraftPickDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "pick_from",
            "original_pick",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of tier
        if self.tier:
            _dict['tier'] = self.tier.to_dict()
        # override the default output from pydantic by calling `to_dict()` of franchise
        if self.franchise:
            _dict['franchise'] = self.franchise.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in players (list)
        _items = []
        if self.players:
            for _item_players in self.players:
                if _item_players:
                    _items.append(_item_players.to_dict())
            _dict['players'] = _items
        # set to None if pick_from (nullable) is None
        # and model_fields_set contains the field
        if self.pick_from is None and "pick_from" in self.model_fields_set:
            _dict['pick_from'] = None

        # set to None if original_pick (nullable) is None
        # and model_fields_set contains the field
        if self.original_pick is None and "original_pick" in self.model_fields_set:
            _dict['original_pick'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DraftPickDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "round": obj.get("round"),
            "number": obj.get("number"),
            "tier": SeasonDraftPickList.from_dict(obj["tier"]) if obj.get("tier") is not None else None,
            "franchise": DraftPickFranchise.from_dict(obj["franchise"]) if obj.get("franchise") is not None else None,
            "future_pick": obj.get("future_pick"),
            "deleted": obj.get("deleted"),
            "pick_from": obj.get("pick_from"),
            "original_pick": obj.get("original_pick"),
            "future_season": obj.get("future_season"),
            "players": [DraftPickLeaguePlayer.from_dict(_item) for _item in obj["players"]] if obj.get("players") is not None else None
        })
        return _obj


