# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from rscapi.models.match_type_enum import MatchTypeEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FlaggedMatch(BaseModel):
    """
    FlaggedMatch
    """ # noqa: E501
    id: StrictInt
    day: StrictInt
    var_date: Optional[datetime] = Field(alias="date")
    match_type: MatchTypeEnum
    match_type_label: StrictStr
    tier: Optional[StrictStr]
    home_team: StrictStr
    away_team: StrictStr
    home_gm_discord_id: Optional[StrictInt]
    away_gm_discord_id: Optional[StrictInt]
    home_wins: Optional[StrictInt]
    away_wins: Optional[StrictInt]
    ballchasing_group: Optional[StrictStr]
    reported_games: StrictInt
    expected_games: StrictInt
    missing_result: StrictBool
    missing_ballchasing_group: StrictBool
    missing_stats: StrictBool
    __properties: ClassVar[List[str]] = ["id", "day", "date", "match_type", "match_type_label", "tier", "home_team", "away_team", "home_gm_discord_id", "away_gm_discord_id", "home_wins", "away_wins", "ballchasing_group", "reported_games", "expected_games", "missing_result", "missing_ballchasing_group", "missing_stats"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FlaggedMatch from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "day",
            "var_date",
            "reported_games",
            "expected_games",
            "missing_result",
            "missing_ballchasing_group",
            "missing_stats",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if var_date (nullable) is None
        # and model_fields_set contains the field
        if self.var_date is None and "var_date" in self.model_fields_set:
            _dict['date'] = None

        # set to None if tier (nullable) is None
        # and model_fields_set contains the field
        if self.tier is None and "tier" in self.model_fields_set:
            _dict['tier'] = None

        # set to None if home_gm_discord_id (nullable) is None
        # and model_fields_set contains the field
        if self.home_gm_discord_id is None and "home_gm_discord_id" in self.model_fields_set:
            _dict['home_gm_discord_id'] = None

        # set to None if away_gm_discord_id (nullable) is None
        # and model_fields_set contains the field
        if self.away_gm_discord_id is None and "away_gm_discord_id" in self.model_fields_set:
            _dict['away_gm_discord_id'] = None

        # set to None if home_wins (nullable) is None
        # and model_fields_set contains the field
        if self.home_wins is None and "home_wins" in self.model_fields_set:
            _dict['home_wins'] = None

        # set to None if away_wins (nullable) is None
        # and model_fields_set contains the field
        if self.away_wins is None and "away_wins" in self.model_fields_set:
            _dict['away_wins'] = None

        # set to None if ballchasing_group (nullable) is None
        # and model_fields_set contains the field
        if self.ballchasing_group is None and "ballchasing_group" in self.model_fields_set:
            _dict['ballchasing_group'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FlaggedMatch from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "day": obj.get("day"),
            "date": obj.get("date"),
            "match_type": obj.get("match_type"),
            "match_type_label": obj.get("match_type_label"),
            "tier": obj.get("tier"),
            "home_team": obj.get("home_team"),
            "away_team": obj.get("away_team"),
            "home_gm_discord_id": obj.get("home_gm_discord_id"),
            "away_gm_discord_id": obj.get("away_gm_discord_id"),
            "home_wins": obj.get("home_wins"),
            "away_wins": obj.get("away_wins"),
            "ballchasing_group": obj.get("ballchasing_group"),
            "reported_games": obj.get("reported_games"),
            "expected_games": obj.get("expected_games"),
            "missing_result": obj.get("missing_result"),
            "missing_ballchasing_group": obj.get("missing_ballchasing_group"),
            "missing_stats": obj.get("missing_stats")
        })
        return _obj


