# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

class FranchiseIdentifier(BaseModel):
    """
    Identifier for the franchise in question. (Provide at least 1)  # noqa: E501
    """
    gm: Optional[StrictInt] = Field(None, description="Discord ID of current GM of the franchise")
    name: Optional[StrictStr] = Field(None, description="Name of the franchise (exact name required).")
    id: Optional[StrictInt] = Field(None, description="ID of the franchise.")
    __properties = ["gm", "name", "id"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> FranchiseIdentifier:
        """Create an instance of FranchiseIdentifier from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> FranchiseIdentifier:
        """Create an instance of FranchiseIdentifier from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return FranchiseIdentifier.parse_obj(obj)

        _obj = FranchiseIdentifier.parse_obj({
            "gm": obj.get("gm"),
            "name": obj.get("name"),
            "id": obj.get("id")
        })
        return _obj


