# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional
from pydantic import BaseModel, StrictBool, StrictInt, StrictStr, constr
from openapi_client.models.franchise_gm import FranchiseGM

class FranchiseList(BaseModel):
    """
    FranchiseList
    """
    id: Optional[StrictInt] = None
    name: Optional[constr(strict=True, min_length=1)] = None
    prefix: Optional[constr(strict=True, min_length=1)] = None
    gm: Optional[FranchiseGM] = None
    league: Optional[StrictInt] = None
    tiers: Optional[Dict[str, Any]] = None
    active: Optional[StrictBool] = None
    teams: Optional[Dict[str, Any]] = None
    logo: Optional[StrictStr] = None
    __properties = ["id", "name", "prefix", "gm", "league", "tiers", "active", "teams", "logo"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> FranchiseList:
        """Create an instance of FranchiseList from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "id",
                            "name",
                            "prefix",
                            "league",
                            "tiers",
                            "active",
                            "teams",
                            "logo",
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of gm
        if self.gm:
            _dict['gm'] = self.gm.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> FranchiseList:
        """Create an instance of FranchiseList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return FranchiseList.parse_obj(obj)

        _obj = FranchiseList.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "prefix": obj.get("prefix"),
            "gm": FranchiseGM.from_dict(obj.get("gm")) if obj.get("gm") is not None else None,
            "league": obj.get("league"),
            "tiers": obj.get("tiers"),
            "active": obj.get("active"),
            "teams": obj.get("teams"),
            "logo": obj.get("logo")
        })
        return _obj


