# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LeagueSeasonStart(BaseModel):
    """
    LeagueSeasonStart
    """ # noqa: E501
    start_date: StrictStr
    end_date: StrictStr
    preseason_start_date: StrictStr
    regular_season_start: StrictStr
    regular_season_end: StrictStr
    draft_date: StrictStr
    signups_close: StrictStr
    season_number: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["start_date", "end_date", "preseason_start_date", "regular_season_start", "regular_season_end", "draft_date", "signups_close", "season_number"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LeagueSeasonStart from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LeagueSeasonStart from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "start_date": obj.get("start_date"),
            "end_date": obj.get("end_date"),
            "preseason_start_date": obj.get("preseason_start_date"),
            "regular_season_start": obj.get("regular_season_start"),
            "regular_season_end": obj.get("regular_season_end"),
            "draft_date": obj.get("draft_date"),
            "signups_close": obj.get("signups_close"),
            "season_number": obj.get("season_number")
        })
        return _obj


