# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, constr

class ListGames(BaseModel):
    """
    ListGames
    """
    winner: constr(strict=True, min_length=1) = Field(...)
    replay_id: Optional[StrictStr] = None
    stats: Optional[StrictStr] = None
    __properties = ["winner", "replay_id", "stats"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ListGames:
        """Create an instance of ListGames from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "replay_id",
                            "stats",
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ListGames:
        """Create an instance of ListGames from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ListGames.parse_obj(obj)

        _obj = ListGames.parse_obj({
            "winner": obj.get("winner"),
            "replay_id": obj.get("replay_id"),
            "stats": obj.get("stats")
        })
        return _obj


