# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MatchScoreReportRequest(BaseModel):
    """
    MatchScoreReportRequest
    """ # noqa: E501
    home_score: StrictInt = Field(description="Number of games Home won.")
    away_score: StrictInt = Field(description="Number of games Away won.")
    executor: StrictInt = Field(description="Person executing the score report")
    ballchasing_group: Annotated[str, Field(min_length=0, strict=True)] = Field(description="ID of the ballchasing group of match results.")
    override: Optional[StrictBool] = Field(default=False, description="Is an admin overriding the score report.")
    __properties: ClassVar[List[str]] = ["home_score", "away_score", "executor", "ballchasing_group", "override"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MatchScoreReportRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MatchScoreReportRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "home_score": obj.get("home_score"),
            "away_score": obj.get("away_score"),
            "executor": obj.get("executor"),
            "ballchasing_group": obj.get("ballchasing_group"),
            "override": obj.get("override") if obj.get("override") is not None else False
        })
        return _obj


