# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from rscapi.models.match_results import MatchResults
from rscapi.models.team import Team
from typing import Optional, Set
from typing_extensions import Self

class Match(BaseModel):
    """
    Match
    """ # noqa: E501
    day: Optional[StrictInt] = None
    var_date: Optional[datetime] = Field(default=None, alias="date")
    game_name: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    game_pass: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    num_games: Optional[StrictInt] = None
    match_format: Optional[StrictStr] = None
    match_type: Optional[StrictStr] = None
    home_team: Team
    away_team: Team
    id: Optional[StrictInt] = None
    results: Optional[MatchResults]
    __properties: ClassVar[List[str]] = ["day", "date", "game_name", "game_pass", "num_games", "match_format", "match_type", "home_team", "away_team", "id", "results"]

    @field_validator('match_format')
    def match_format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['GMS', 'BO3', 'BO5', 'BO7']):
            raise ValueError("must be one of enum values ('GMS', 'BO3', 'BO5', 'BO7')")
        return value

    @field_validator('match_type')
    def match_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['REG', 'PRE', 'PST', 'FNL']):
            raise ValueError("must be one of enum values ('REG', 'PRE', 'PST', 'FNL')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Match from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "day",
            "var_date",
            "game_name",
            "game_pass",
            "num_games",
            "match_format",
            "match_type",
            "id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of home_team
        if self.home_team:
            _dict['home_team'] = self.home_team.to_dict()
        # override the default output from pydantic by calling `to_dict()` of away_team
        if self.away_team:
            _dict['away_team'] = self.away_team.to_dict()
        # override the default output from pydantic by calling `to_dict()` of results
        if self.results:
            _dict['results'] = self.results.to_dict()
        # set to None if var_date (nullable) is None
        # and model_fields_set contains the field
        if self.var_date is None and "var_date" in self.model_fields_set:
            _dict['date'] = None

        # set to None if results (nullable) is None
        # and model_fields_set contains the field
        if self.results is None and "results" in self.model_fields_set:
            _dict['results'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Match from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "day": obj.get("day"),
            "date": obj.get("date"),
            "game_name": obj.get("game_name"),
            "game_pass": obj.get("game_pass"),
            "num_games": obj.get("num_games"),
            "match_format": obj.get("match_format"),
            "match_type": obj.get("match_type"),
            "home_team": Team.from_dict(obj["home_team"]) if obj.get("home_team") is not None else None,
            "away_team": Team.from_dict(obj["away_team"]) if obj.get("away_team") is not None else None,
            "id": obj.get("id"),
            "results": MatchResults.from_dict(obj["results"]) if obj.get("results") is not None else None
        })
        return _obj


