# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PlayerMMRTypeEnum(str, Enum):
    """
    * `SN` - Season * `HS` - Historical * `DA` - Daily
    """

    """
    allowed enum values
    """
    SN = 'SN'
    HS = 'HS'
    DA = 'DA'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PlayerMMRTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


