# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr

class TemporaryFASub(BaseModel):
    """
    Temporarily sub a free agent to a team.  # noqa: E501
    """
    player_in: StrictInt = Field(..., description="Specific player to perform transaction on.")
    player_out: StrictInt = Field(..., description="Specific player to perform transaction on.")
    league: StrictInt = Field(..., description="ID of the league transaction is for.")
    executor: StrictInt = Field(..., description="Discord ID of specific member who ran the transaction.")
    notes: Optional[StrictStr] = Field(None, description="Notes for the transaction from the TM running it.")
    admin_override: Optional[StrictBool] = Field(None, description="Boolean indicating whether or not an admin is overriding this command.")
    __properties = ["player_in", "player_out", "league", "executor", "notes", "admin_override"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TemporaryFASub:
        """Create an instance of TemporaryFASub from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TemporaryFASub:
        """Create an instance of TemporaryFASub from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TemporaryFASub.parse_obj(obj)

        _obj = TemporaryFASub.parse_obj({
            "player_in": obj.get("player_in"),
            "player_out": obj.get("player_out"),
            "league": obj.get("league"),
            "executor": obj.get("executor"),
            "notes": obj.get("notes"),
            "admin_override": obj.get("admin_override")
        })
        return _obj


