# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictInt, constr

class Tier(BaseModel):
    """
    Tier
    """
    id: Optional[StrictInt] = None
    name: Optional[constr(strict=True, min_length=1)] = None
    color: Optional[StrictInt] = None
    position: Optional[StrictInt] = None
    __properties = ["id", "name", "color", "position"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Tier:
        """Create an instance of Tier from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "id",
                            "name",
                            "color",
                            "position",
                          },
                          exclude_none=True)
        # set to None if color (nullable) is None
        # and __fields_set__ contains the field
        if self.color is None and "color" in self.__fields_set__:
            _dict['color'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Tier:
        """Create an instance of Tier from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Tier.parse_obj(obj)

        _obj = Tier.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "color": obj.get("color"),
            "position": obj.get("position")
        })
        return _obj


