# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from rscapi.models.draft_pick_trade import DraftPickTrade
from rscapi.models.trade_player import TradePlayer
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TradeItem(BaseModel):
    """
    TradeItem
    """ # noqa: E501
    player: Optional[TradePlayer] = None
    pick: Optional[DraftPickTrade] = None
    __properties: ClassVar[List[str]] = ["player", "pick"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TradeItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of player
        if self.player:
            _dict['player'] = self.player.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pick
        if self.pick:
            _dict['pick'] = self.pick.to_dict()
        # set to None if player (nullable) is None
        # and model_fields_set contains the field
        if self.player is None and "player" in self.model_fields_set:
            _dict['player'] = None

        # set to None if pick (nullable) is None
        # and model_fields_set contains the field
        if self.pick is None and "pick" in self.model_fields_set:
            _dict['pick'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TradeItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "player": TradePlayer.from_dict(obj["player"]) if obj.get("player") is not None else None,
            "pick": DraftPickTrade.from_dict(obj["pick"]) if obj.get("pick") is not None else None
        })
        return _obj


