# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class TransactionPick(BaseModel):
    """
    TransactionPick
    """ # noqa: E501
    id: Optional[StrictInt] = None
    number: Optional[StrictInt] = Field(default=None, description="Pick in the specific tier.")
    round: Optional[StrictInt] = Field(default=None, description="Specific round in the tier.")
    tier: Optional[StrictStr] = None
    future_pick: Optional[StrictBool] = None
    future_season: Optional[StrictInt] = None
    pick_from: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="Prefix of franchise this pick came from (if any)")
    original_pick: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="Prefix of franchise this pick originally came from (if any)")
    __properties: ClassVar[List[str]] = ["id", "number", "round", "tier", "future_pick", "future_season", "pick_from", "original_pick"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransactionPick from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "number",
            "round",
            "tier",
            "future_pick",
            "future_season",
            "pick_from",
            "original_pick",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if pick_from (nullable) is None
        # and model_fields_set contains the field
        if self.pick_from is None and "pick_from" in self.model_fields_set:
            _dict['pick_from'] = None

        # set to None if original_pick (nullable) is None
        # and model_fields_set contains the field
        if self.original_pick is None and "original_pick" in self.model_fields_set:
            _dict['original_pick'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransactionPick from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "number": obj.get("number"),
            "round": obj.get("round"),
            "tier": obj.get("tier"),
            "future_pick": obj.get("future_pick"),
            "future_season": obj.get("future_season"),
            "pick_from": obj.get("pick_from"),
            "original_pick": obj.get("original_pick")
        })
        return _obj


