# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from rscapi.models.league_player import LeaguePlayer
from rscapi.models.transaction_franchise import TransactionFranchise
from rscapi.models.transaction_team import TransactionTeam
from rscapi.models.waiver_claim_response_status_enum import WaiverClaimResponseStatusEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WaiverClaimResponse(BaseModel):
    """
    WaiverClaimResponse
    """ # noqa: E501
    id: Optional[StrictInt] = None
    season: Optional[StrictInt] = None
    tier: Optional[StrictInt] = None
    franchise: TransactionFranchise
    team: TransactionTeam
    player: LeaguePlayer
    drop_player: Optional[LeaguePlayer]
    status: Optional[WaiverClaimResponseStatusEnum] = None
    created_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "season", "tier", "franchise", "team", "player", "drop_player", "status", "created_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WaiverClaimResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "season",
            "tier",
            "status",
            "created_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of franchise
        if self.franchise:
            _dict['franchise'] = self.franchise.to_dict()
        # override the default output from pydantic by calling `to_dict()` of team
        if self.team:
            _dict['team'] = self.team.to_dict()
        # override the default output from pydantic by calling `to_dict()` of player
        if self.player:
            _dict['player'] = self.player.to_dict()
        # override the default output from pydantic by calling `to_dict()` of drop_player
        if self.drop_player:
            _dict['drop_player'] = self.drop_player.to_dict()
        # set to None if drop_player (nullable) is None
        # and model_fields_set contains the field
        if self.drop_player is None and "drop_player" in self.model_fields_set:
            _dict['drop_player'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WaiverClaimResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "season": obj.get("season"),
            "tier": obj.get("tier"),
            "franchise": TransactionFranchise.from_dict(obj["franchise"]) if obj.get("franchise") is not None else None,
            "team": TransactionTeam.from_dict(obj["team"]) if obj.get("team") is not None else None,
            "player": LeaguePlayer.from_dict(obj["player"]) if obj.get("player") is not None else None,
            "drop_player": LeaguePlayer.from_dict(obj["drop_player"]) if obj.get("drop_player") is not None else None,
            "status": obj.get("status"),
            "created_at": obj.get("created_at")
        })
        return _obj


