# coding: utf-8

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class WaiverClaimResponseStatusEnum(str, Enum):
    """
    * `pending` - Pending * `won` - Won * `lost` - Lost * `invalid` - Invalid * `cancelled` - Cancelled
    """

    """
    allowed enum values
    """
    PENDING = 'pending'
    WON = 'won'
    LOST = 'lost'
    INVALID = 'invalid'
    CANCELLED = 'cancelled'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WaiverClaimResponseStatusEnum from a JSON string"""
        return cls(json.loads(json_str))


