# coding: utf-8

# flake8: noqa

"""
    RSC API Docs

    RSC API Documentation

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from rscapi.api.franchises_api import FranchisesApi
from rscapi.api.league_players_api import LeaguePlayersApi
from rscapi.api.leagues_api import LeaguesApi
from rscapi.api.matches_api import MatchesApi
from rscapi.api.members_api import MembersApi
from rscapi.api.numbers_api import NumbersApi
from rscapi.api.seasons_api import SeasonsApi
from rscapi.api.teams_api import TeamsApi
from rscapi.api.tiers_api import TiersApi
from rscapi.api.tracker_links_api import TrackerLinksApi
from rscapi.api.transactions_api import TransactionsApi

# import ApiClient
from rscapi.api_response import ApiResponse
from rscapi.api_client import ApiClient
from rscapi.configuration import Configuration
from rscapi.exceptions import OpenApiException
from rscapi.exceptions import ApiTypeError
from rscapi.exceptions import ApiValueError
from rscapi.exceptions import ApiKeyError
from rscapi.exceptions import ApiAttributeError
from rscapi.exceptions import ApiException

# import models into sdk package
from rscapi.models.add_tier_to_league import AddTierToLeague
from rscapi.models.base_team import BaseTeam
from rscapi.models.bulk_mmr_schema_submission import BulkMMRSchemaSubmission
from rscapi.models.cut_a_player_from_a_league import CutAPlayerFromALeague
from rscapi.models.deleted import Deleted
from rscapi.models.elevated_role import ElevatedRole
from rscapi.models.error import Error
from rscapi.models.expire_a_player_sub import ExpireAPlayerSub
from rscapi.models.franchise import Franchise
from rscapi.models.franchise_gm import FranchiseGM
from rscapi.models.franchise_league import FranchiseLeague
from rscapi.models.franchise_list import FranchiseList
from rscapi.models.franchise_logo import FranchiseLogo
from rscapi.models.franchise_standings import FranchiseStandings
from rscapi.models.franchise_team import FranchiseTeam
from rscapi.models.franchise_tier import FranchiseTier
from rscapi.models.game import Game
from rscapi.models.high_level_match import HighLevelMatch
from rscapi.models.intent_to_play_schema import IntentToPlaySchema
from rscapi.models.league import League
from rscapi.models.league_data import LeagueData
from rscapi.models.league_player import LeaguePlayer
from rscapi.models.league_player_member import LeaguePlayerMember
from rscapi.models.league_players_list200_response import LeaguePlayersList200Response
from rscapi.models.list_games import ListGames
from rscapi.models.list_match_results import ListMatchResults
from rscapi.models.match import Match
from rscapi.models.match_list import MatchList
from rscapi.models.match_results import MatchResults
from rscapi.models.matches_list200_response import MatchesList200Response
from rscapi.models.member import Member
from rscapi.models.member_tracker import MemberTracker
from rscapi.models.members_list200_response import MembersList200Response
from rscapi.models.player import Player
from rscapi.models.player_franchise import PlayerFranchise
from rscapi.models.player_mmr import PlayerMMR
from rscapi.models.player_season_stats import PlayerSeasonStats
from rscapi.models.player_season_stats_in_depth import PlayerSeasonStatsInDepth
from rscapi.models.player_signup_schema import PlayerSignupSchema
from rscapi.models.player_team import PlayerTeam
from rscapi.models.player_transaction_updates import PlayerTransactionUpdates
from rscapi.models.previous_team import PreviousTeam
from rscapi.models.re_sign_player import ReSignPlayer
from rscapi.models.rebrand_a_franchise import RebrandAFranchise
from rscapi.models.remove_tier_from_a_league import RemoveTierFromALeague
from rscapi.models.schedule_ingest_request_body import ScheduleIngestRequestBody
from rscapi.models.season import Season
from rscapi.models.season_league import SeasonLeague
from rscapi.models.season_schedule import SeasonSchedule
from rscapi.models.season_tier_data import SeasonTierData
from rscapi.models.sign_a_player_to_a_team_in_a_league import SignAPlayerToATeamInALeague
from rscapi.models.simple_response import SimpleResponse
from rscapi.models.start_new_season import StartNewSeason
from rscapi.models.team import Team
from rscapi.models.team_details import TeamDetails
from rscapi.models.team_franchise import TeamFranchise
from rscapi.models.team_list import TeamList
from rscapi.models.team_season_stats import TeamSeasonStats
from rscapi.models.temporary_fa_sub import TemporaryFASub
from rscapi.models.tier import Tier
from rscapi.models.tracker_link import TrackerLink
from rscapi.models.tracker_link_invalidate_object import TrackerLinkInvalidateObject
from rscapi.models.tracker_link_stats import TrackerLinkStats
from rscapi.models.tracker_mmr import TrackerMMR
from rscapi.models.transaction_franchise import TransactionFranchise
from rscapi.models.transaction_response import TransactionResponse
from rscapi.models.transaction_team import TransactionTeam
from rscapi.models.transfer_franchise import TransferFranchise
from rscapi.models.update_member_rsc_name import UpdateMemberRSCName
